Initial work to use GSSCredential interface
IBM/JTOpen pull request #75
Opened 2023-05-30 17:25 UTC by worksofliam

Signed-off-by: Liam Allan <mrliamallan@live.co.uk>

2023-05-30 17:32 UTC, worksofliam commented
Regarding this line of code: https://github.com/worksofliam/JTOpen/blob/fix/50_gsscredential/src/main/java/com/ibm/as400/access/AS400ImplProxy.java#L284

> for now, just change the setGSSCredential signature, but dang, we should open an issue to revisit this

2023-05-30 17:32 UTC, ThePrez requested changes

2023-05-30 17:32 UTC, ThePrez commented on src/main/java/com/ibm/as400/access/AS400.java
>       @param  gssCredential  The GSS credential object.  The object's type must be org.ietf.jgss.GSSCredential, the object is set to type Object only to avoid a JDK release dependency.
can clean up this comment now

2023-06-07 22:10 UTC, ThePrez commented on src/main/java/com/ibm/as400/access/AS400.java
>       @param  gssCredential  The GSS credential object.  The object's type must be org.ietf.jgss.GSSCredential, the object is set to type Object only to avoid a JDK release dependency.
Cleaned up.

2023-06-07 22:11 UTC, ThePrez commented
@worksofliam , the changes LGTM! 
I see we should also fix up `setGSSManager()`. Should you handle here or should we do a separate issue/pr?

2023-06-07 22:11 UTC, ThePrez approved these changes

2023-06-08 14:58 UTC, merged